apiVersion: v1
kind: Service
metadata:
  name: console-np
  namespace: console-system
spec:
  type: NodePort
  ports:
    - name: "https"
      port: 443
      targetPort: 443
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    app: console
    hypercloud: ui

---

