kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "console.fullname" . }}
  labels:
  {{- include "console.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "console.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "console.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}